#!/usr/bin/env bun
// @ts-nocheck -- script standalone execute par bun, pas type-check
// Hook SessionStart: alloue des ports dev libres pour chaque projet/worktree Vibe Stack.
//
// Idempotent : si .env.local contient deja FRONTEND_PORT/BACKEND_PORT et qu'ils
// sont toujours libres, on les conserve. Sinon on scanne a partir de 5173/3000.
//
// Detection projet : early exit si .flow/project.json absent (= pas un projet Vibe Stack).

import { createServer } from 'node:net'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, resolve } from 'node:path'
import { execSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'

const PROJECT_ROOT = process.env.CLAUDE_PROJECT_DIR ?? process.cwd()
const FLOW_MARKER = join(PROJECT_ROOT, '.flow/project.json')
const ENV = join(PROJECT_ROOT, '.env')
const ENV_EXAMPLE = join(PROJECT_ROOT, '.env.example')
const ENV_LOCAL = join(PROJECT_ROOT, '.env.local')
const LAUNCH_JSON = join(PROJECT_ROOT, '.claude/launch.json')

const FRONTEND_DEFAULT = 5173
const BACKEND_DEFAULT = 3000

if (!existsSync(FLOW_MARKER)) {
  // Pas un projet Vibe Stack -> on ne touche a rien
  process.exit(0)
}

function isFree(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const server = createServer()
    server.once('error', () => resolve(false))
    server.once('listening', () => server.close(() => resolve(true)))
    server.listen(port, '127.0.0.1')
  })
}

async function findFreePort(start: number, exclude: Set<number>): Promise<number> {
  let p = start
  while (exclude.has(p) || !(await isFree(p))) p++
  return p
}

function parseEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of content.split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/)
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
  return out
}

function upsertEnv(content: string, updates: Record<string, string>): string {
  const lines = content.split('\n')
  const seen = new Set<string>()
  const next = lines.map((line) => {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=/)
    if (m && updates[m[1]] !== undefined) {
      seen.add(m[1])
      return `${m[1]}=${updates[m[1]]}`
    }
    return line
  })
  for (const [k, v] of Object.entries(updates)) {
    if (!seen.has(k)) next.push(`${k}=${v}`)
  }
  return next.join('\n').replace(/\n+$/, '') + '\n'
}

async function pickPort(
  current: number,
  fallbackStart: number,
  exclude: Set<number>
): Promise<number> {
  if (current && !exclude.has(current) && (await isFree(current))) return current
  return findFreePort(fallbackStart, exclude)
}

function findMainRepoEnv(): string | null {
  try {
    const commonDir = execSync('git rev-parse --git-common-dir', {
      cwd: PROJECT_ROOT,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
    const absCommonDir = isAbsolute(commonDir) ? commonDir : resolve(PROJECT_ROOT, commonDir)
    const mainRoot = dirname(absCommonDir)
    if (resolve(mainRoot) === resolve(PROJECT_ROOT)) return null // pas un worktree
    const mainEnv = join(mainRoot, '.env')
    return existsSync(mainEnv) ? mainEnv : null
  } catch {
    return null
  }
}

function generateSecret(): string {
  return randomBytes(32).toString('hex') // 64 chars hex
}

function bootstrapEnv(): void {
  if (!existsSync(ENV_EXAMPLE)) return

  // 1. Si .env n'existe pas, copier celui du repo principal s'il existe
  if (!existsSync(ENV)) {
    const mainEnv = findMainRepoEnv()
    if (mainEnv) writeFileSync(ENV, readFileSync(mainEnv))
  }

  // 2. Compléter avec les vars manquantes de .env.example
  const exampleContent = readFileSync(ENV_EXAMPLE, 'utf-8')
  const envContent = existsSync(ENV) ? readFileSync(ENV, 'utf-8') : ''
  const envVars = parseEnv(envContent)

  const additions: string[] = []
  for (const line of exampleContent.split('\n')) {
    // Match "KEY=value" ou "# KEY=value" (commentee)
    const match = line.match(/^#?\s*([A-Z_][A-Z0-9_]*)=(.*)$/)
    if (!match) continue
    const [, key, rawValue] = match
    if (envVars[key] !== undefined) continue // deja defini

    let value: string
    if (key === 'JWT_SECRET' || key === 'JWT_REFRESH_SECRET') {
      value = `"${generateSecret()}"`
    } else {
      value = rawValue.trim()
    }
    additions.push(`${key}=${value}`)
  }

  if (additions.length === 0) return

  const prefix = envContent === '' || envContent.endsWith('\n') ? '' : '\n'
  const block = `\n# Auto-generated by vibe-stack hook (${new Date().toISOString()})\n${additions.join('\n')}\n`
  writeFileSync(ENV, envContent + prefix + block)
}

async function main() {
  bootstrapEnv()

  const existingContent = existsSync(ENV_LOCAL) ? readFileSync(ENV_LOCAL, 'utf-8') : ''
  const existing = parseEnv(existingContent)

  const currentFrontend = parseInt(existing.FRONTEND_PORT ?? '0', 10) || 0
  const currentBackend = parseInt(existing.BACKEND_PORT ?? '0', 10) || 0

  const frontendPort = await pickPort(currentFrontend, FRONTEND_DEFAULT, new Set([currentBackend]))
  const backendPort = await pickPort(currentBackend, BACKEND_DEFAULT, new Set([frontendPort]))

  const updates: Record<string, string> = {
    FRONTEND_PORT: String(frontendPort),
    BACKEND_PORT: String(backendPort),
    FRONTEND_URL: `http://localhost:${frontendPort}`,
  }
  const nextContent = upsertEnv(existingContent, updates)
  if (nextContent !== existingContent) writeFileSync(ENV_LOCAL, nextContent)

  mkdirSync(dirname(LAUNCH_JSON), { recursive: true })

  let launch: { version: string; configurations: Array<Record<string, unknown>> } = {
    version: '0.0.1',
    configurations: [],
  }
  if (existsSync(LAUNCH_JSON)) {
    try {
      const parsed = JSON.parse(readFileSync(LAUNCH_JSON, 'utf-8'))
      launch = {
        version: typeof parsed?.version === 'string' ? parsed.version : '0.0.1',
        configurations: Array.isArray(parsed?.configurations) ? parsed.configurations : [],
      }
    } catch {
      // launch.json corrompu : on repart d'un launch vide
    }
  }

  const managed = new Set(['web', 'api'])
  const preserved = launch.configurations.filter((c) => !managed.has(c?.name as string))

  launch.configurations = [
    ...preserved,
    {
      name: 'web',
      runtimeExecutable: 'bun',
      runtimeArgs: ['run', 'dev:web'],
      port: frontendPort,
    },
    {
      name: 'api',
      runtimeExecutable: 'bun',
      runtimeArgs: ['run', 'dev:api'],
      port: backendPort,
    },
  ]

  writeFileSync(LAUNCH_JSON, JSON.stringify(launch, null, 2) + '\n')

  console.log(`Vibe Stack ports: web=${frontendPort}, api=${backendPort}`)
}

main()
